language: python
python:
  - "3.5"
  - "3.6.6"

# command to install dependencies and tests tooling
install:
  - pip install -e .[tests]

# command to run tests
script:
  - make test
  - make criticalint

#command to generate documentation
#after_success:
#  - make doc
#  - make metrics
